FROM node:20-alpine AS build
WORKDIR /ui
COPY jarvis-ui/package.json /ui/package.json
RUN npm install
COPY jarvis-ui /ui
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /ui/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
